### ISSUE TITLE
Only able to read 2D formats (QR, Data Matrix, etc.)

### ISSUE THREAD

**Issue by amitaigat** [ideacreation/react-native-barcodescanner#37]
It seems I'm unable to read any of the supported formats except for the 2D ones. Maybe I'm missing something but the QR Code and the other 2D formats are all working great! However, when I try to read a Code 39 for example, it simply doesn't get picked up. Any thoughts?

**Comment by ThaJay** [comment]
for me, EAN_13 only reads vertical in portrait or horizontal in landscape.

**Comment by ddzyndra** [comment]
Also same issue, can't read EAN_13 in portrait mode. Can it be fixed somehow ?

**Comment by Arwiz** [comment]
I am able to scan only QR code

**Comment by AnujWizni** [comment]
How to support multiple barcode types as i am only able to scan QR codes

**Comment by ddzyndra** [comment]
Try to scan EAN_13 in landscape mode

**Comment by andreaskeller** [comment]
You could only scan 1D barcodes in landscape mode. With the newest version they can be scanned both in portrait and landscape mode.

**Comment by ThaJay** [comment]
This is actually not the case. Before the change it only scanned 1D barcodes vertically in portrait mode. and horizontally in landscape mode. Now it only scans them horizontally in portrait mode and landscape mode.

There is still no way it scans a 1D barcode at different angles. Also, the stretched (instead of fitted) camera view looks even worse in landscape mode now. I like the old behaviour better to be honest. I can see the logic of having to align the screen to the length of the barcode.

Being able to scan 1D barcodes both horizontally and vertically would be best. As you chose this solution, I reckon that's not in your control?
